[versions]
accompanistPermissions = "0.37.3"
composeRatingbar = "1.3.12"
fengdaiComposeMedia = "0.4.0"
deepseekKotlin = "0.1.0"
hiltCompiler = "2.57.1"
hiltNavigationCompose = "1.2.0"
kotlinxCollectionsImmutable = "0.4.0"
runtimeLivedata = "1.8.2"
serializationJson = "1.7.3"
kotlin = "2.2.10"
coroutines = "1.10.2"
activityCompose = "1.10.1"
composeUtil = "1.8.2"
composeBom = "2025.05.01"
composeMaterial = "1.3.2"
room = "2.7.2"
zelory = "3.0.1"
media3 = "1.7.1"
coil = "2.7.0"
paging = "3.3.6"
googleMapCompose = "2.11.4"
ktorVer = "3.2.3"
playServicesMaps = "19.2.0"
playServicesLocation = "21.3.0"
places = "4.1.0"
androidxWork = "2.10.1"
googleGms = "21.3.0"
imageCropperVersion = "4.5.0"
datastore = "1.1.7"
androidxCoreKtx = "1.16.0"
androidxLifecycleKtx = "2.9.0"
devtools = "2.2.10-2.0.2"
application = "8.9.3"
kotlinxDatetime = "0.7.1"
testJunit = "4.13.2"
testJunitExt = "1.2.1"
espressoCore = "3.6.1"
kotlinCompiler = "1.5.3"
okhttp = "4.11.0"
datetime = "0.4.1"
retrofit = "2.9.0"
okHttp3 = "5.1.0"
firebase = "24.1.2"
gsm = "4.4.3"
dagger = "2.49"
inject = "1"
lifecycleViewmodelCompose = "2.9.3"
navigation = "2.9.3"
googlePlayVer = "2.1.0"
googlePlayReviewVer = "2.0.2"
autolinktextVer = "2.0.2"
composeWebViewVer = "0.33.6"
composeMaterialCore = "1.5.0"
yandexMetrica = "5.3.7"
hiltAndroid = "2.57.1"
media3Exoplayer = "1.8.0"
media3Ui = "1.8.0"

[libraries]
#   Kotlin
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
deepseek-kotlin = { module = "com.github.oremif:deepseek-kotlin", version.ref = "deepseekKotlin" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltCompiler" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

#   Androidx core-ktx
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCoreKtx" }

#   Androidx runtime-ktx
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycleKtx" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycleKtx" }

#   Datastore
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

#   Compose
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material = {group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "composeUtil" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

#   Coroutines
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-android-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Image Cropper
image-cropper = { group = "com.vanniktech", name = "android-image-cropper", version.ref = "imageCropperVersion" }

##   Dagger2
#dagger-core = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
#dagger-android = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
#dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
#javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }
#dagger-android-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
#dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "dagger" }

# Video
fengdai-compose-media = { group = "com.github.fengdai.compose", name = "media", version.ref = "fengdaiComposeMedia" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }

#   Retrofit
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }

#   OkHttp3
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp3" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp3" }

#   Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-common = { group = "androidx.navigation", name = "navigation-common-ktx", version.ref = "navigation" }

#   Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }


#   Zelory
zelory-compressor = { group = "id.zelory", name = "compressor", version.ref = "zelory" }

#   Firebase
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebase" }

#   Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

#   Paging
paging-compose = { group = "androidx.paging", name = "paging-compose-android", version.ref = "paging" }

#   AndroidxWork runtime
androidxWork-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }

#  Kotlinx-datetime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Yandex Metrica
yandex-metrica = { module = "com.yandex.android:mobmetricalib", version.ref = "yandexMetrica" }


#   Google Map Kit
google-maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "googleMapCompose" }
google-maps-compose-utils = { group = "com.google.maps.android", name = "maps-compose-utils", version.ref = "googleMapCompose"}
google-maps-compose-widgets = {group = "com.google.maps.android", name = "maps-compose-widgets", version.ref = "googleMapCompose"}
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktorVer" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktorVer" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktorVer" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktorVer" }

#   Tests Compose
test-compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

#   Tests
test-junit = { module = "junit:junit", version.ref = "testJunit" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "testJunitExt" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

#   Google play
google-play-feature = { group = "com.google.android.play", name = "feature-delivery", version.ref = "googlePlayVer" }
google-play-feature-ktx = { group = "com.google.android.play", name = "feature-delivery-ktx", version.ref = "googlePlayVer" }
google-play-review = { group = "com.google.android.play", name = "review", version.ref = "googlePlayReviewVer" }
google-play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "googlePlayReviewVer" }
google-play-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "googlePlayVer" }
google-play-app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "googlePlayVer" }

#   AutoLinkText
autolinktext = { group = "sh.calvin.autolinktext", name = "autolinktext", version.ref = "autolinktextVer" }

#Compose-webview
compose-webview = { group = "io.github.kevinnzou", name = "compose-webview", version.ref = "composeWebViewVer" }

#RatingBar
compose-ratingbar = { module = "com.github.a914-gowtham:compose-ratingbar", version.ref = "composeRatingbar" }

androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-compose-material-core = { group = "androidx.wear.compose", name = "compose-material-core", version.ref = "composeMaterialCore" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }

[plugins]
application = { id = "com.android.application", version.ref = "application" }
library = { id = "com.android.library", version.ref = "application" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
devtools = { id = "com.google.devtools.ksp", version.ref = "devtools" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
googleServicePlugin = { id = "com.google.gms.google-services", version.ref = "gsm" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinKapt = { id = "kotlin-kapt" }
kotlinParcelize = { id = "kotlin-parcelize" }
kotlinSerializationPlugin = { id = "kotlinx-serialization" }

